/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Totem_3D_Oficial.glb --transform --dest src/components/ 
Files: public/models/Totem_3D_Oficial.glb [147.62KB] > C:\Users\Aluno\Desktop\SinalizaAI\SinalizaAI_code\Front_end\Totem_3D_Oficial-transformed.glb [7.87KB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Totem_3D_Oficial-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[-0.089, -0.066, 0.111]} />
      <mesh geometry={nodes.Cubo.geometry} material={nodes.Cubo.material} position={[1.408, -4.342, 2.901]} scale={[5, 1.8, 1.5]} />
    </group>
  )
}

useGLTF.preload('/Totem_3D_Oficial-transformed.glb')
